### ISSUE TITLE
Set up a mail service

### ISSUE THREAD

**Issue by duydang2311** [hcmute-human/issues#8]
## Overview

We need to send emails.

## Task list

- [x] Use a SMTP server.
- [x] Send email with any supported types of content.
- [x] REST endpoint for sending email.

**Comment by NNQA** [comment]
List mail services:
1. Gmail stmp server : If you have a free account, you can send a request to email for up to 500 emails. but it can't However, you cannot send alias emails or private domain emails through Gmail SMTP Server.
2. Send grid: It can free request up to 100 emails per day. 
3. STMP2GO: Free plan offers 1000 emails per month.

**Comment by duydang2311** [comment]
Going with Gmail SMTP server for now.
